# Generated by Django 3.1.7 on 2021-02-28 14:18

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210226_2032'),
        ('posts', '0011_auto_20210228_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.file_path_dir),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='accounts.Profile'),
        ),
    ]
