# Generated by Django 3.1.5 on 2021-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210307_2152'),
        ('posts', '0020_auto_20210307_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='accounts.Profile'),
        ),
    ]
