# Generated by Django 3.1.5 on 2021-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210226_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_date',
            new_name='token_expiration_date',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
