# Generated by Django 3.1.5 on 2021-03-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210304_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiration_date',
            field=models.DateTimeField(),
        ),
    ]
